import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
} from '@react-pdf/renderer'
import { formatCurrency } from '@/lib/currency'

const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontFamily: 'Helvetica',
    backgroundColor: '#ffffff',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 30,
    paddingBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#e5e7eb',
  },
  company: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#16a34a',
  },
  payslipTitle: {
    fontSize: 12,
    color: '#6b7280',
    marginTop: 4,
  },
  month: {
    fontSize: 12,
    color: '#6b7280',
    textAlign: 'right',
  },
  section: {
    marginBottom: 20,
  },
  sectionTitle: {
    fontSize: 11,
    fontWeight: 'bold',
    color: '#374151',
    marginBottom: 8,
    paddingBottom: 4,
    borderBottomWidth: 1,
    borderBottomColor: '#f3f4f6',
  },
  employeeInfo: {
    flexDirection: 'row',
    gap: 40,
    marginBottom: 24,
    padding: 16,
    backgroundColor: '#f9fafb',
    borderRadius: 8,
  },
  infoBlock: {
    flex: 1,
  },
  infoLabel: {
    fontSize: 9,
    color: '#9ca3af',
    marginBottom: 2,
  },
  infoValue: {
    fontSize: 11,
    color: '#111827',
    fontWeight: 'bold',
  },
  row: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 6,
    borderBottomWidth: 1,
    borderBottomColor: '#f9fafb',
  },
  rowLabel: {
    fontSize: 10,
    color: '#6b7280',
  },
  rowValue: {
    fontSize: 10,
    color: '#111827',
  },
  rowValueGreen: {
    fontSize: 10,
    color: '#16a34a',
  },
  rowValueRed: {
    fontSize: 10,
    color: '#dc2626',
  },
  totalRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 10,
    marginTop: 8,
    paddingHorizontal: 12,
    backgroundColor: '#f0fdf4',
    borderRadius: 6,
  },
  totalLabel: {
    fontSize: 13,
    fontWeight: 'bold',
    color: '#111827',
  },
  totalValue: {
    fontSize: 13,
    fontWeight: 'bold',
    color: '#16a34a',
  },
  footer: {
    marginTop: 40,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: '#e5e7eb',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  footerText: {
    fontSize: 9,
    color: '#9ca3af',
  },
  generatedBy: {
    fontSize: 9,
    color: '#16a34a',
  },
})

const months = [
  'January', 'February', 'March', 'April', 'May', 'June',
  'July', 'August', 'September', 'October', 'November', 'December'
]

interface Props {
  employee: any
  business: any
  record: any
}

export default function PayslipPDF({ employee, business, record }: Props) {
  const format = (amount: number) => formatCurrency(amount, business?.currency || 'INR')

  return (
    <Document>
      <Page size="A4" style={styles.page}>

        {/* Header */}
        <View style={styles.header}>
          <View>
            <Text style={styles.company}>{business?.name}</Text>
            <Text style={styles.payslipTitle}>Payslip</Text>
          </View>
          <View>
            <Text style={styles.month}>
              {months[record.month - 1]} {record.year}
            </Text>
            <Text style={[styles.month, { marginTop: 4 }]}>
              Generated by PayLeaf
            </Text>
          </View>
        </View>

        {/* Employee Info */}
        <View style={styles.employeeInfo}>
          <View style={styles.infoBlock}>
            <Text style={styles.infoLabel}>Employee Name</Text>
            <Text style={styles.infoValue}>{employee?.name}</Text>
          </View>
          <View style={styles.infoBlock}>
            <Text style={styles.infoLabel}>Designation</Text>
            <Text style={styles.infoValue}>{employee?.role || '—'}</Text>
          </View>
          <View style={styles.infoBlock}>
            <Text style={styles.infoLabel}>Pay Period</Text>
            <Text style={styles.infoValue}>
              {months[record.month - 1]} {record.year}
            </Text>
          </View>
          <View style={styles.infoBlock}>
            <Text style={styles.infoLabel}>Days Present</Text>
            <Text style={styles.infoValue}>
              {record.days_present} / {record.working_days}
            </Text>
          </View>
        </View>

        {/* Earnings */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>EARNINGS</Text>
          <View style={styles.row}>
            <Text style={styles.rowLabel}>Base Salary</Text>
            <Text style={styles.rowValueGreen}>
              {format(Number(record.basic_salary))}
            </Text>
          </View>
          {record.hra > 0 && (
            <View style={styles.row}>
              <Text style={styles.rowLabel}>HRA</Text>
              <Text style={styles.rowValueGreen}>
                +{format(Number(record.hra))}
              </Text>
            </View>
          )}
          {record.allowances > 0 && (
            <View style={styles.row}>
              <Text style={styles.rowLabel}>Allowances</Text>
              <Text style={styles.rowValueGreen}>
                +{format(Number(record.allowances))}
              </Text>
            </View>
          )}
          {record.overtime_hours > 0 && (
            <View style={styles.row}>
              <Text style={styles.rowLabel}>
                Overtime ({record.overtime_hours} hrs)
              </Text>
              <Text style={styles.rowValueGreen}>
                +{format(record.overtime_hours * record.overtime_rate)}
              </Text>
            </View>
          )}
          {record.bonus > 0 && (
            <View style={styles.row}>
              <Text style={styles.rowLabel}>Bonus</Text>
              <Text style={styles.rowValueGreen}>
                +{format(Number(record.bonus))}
              </Text>
            </View>
          )}
          <View style={styles.row}>
            <Text style={[styles.rowLabel, { fontWeight: 'bold', color: '#374151' }]}>
              Gross Salary
            </Text>
            <Text style={[styles.rowValue, { fontWeight: 'bold' }]}>
              {format(Number(record.gross_salary))}
            </Text>
          </View>
        </View>

        {/* Deductions */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>DEDUCTIONS</Text>
          {record.pf_deduction > 0 && (
            <View style={styles.row}>
              <Text style={styles.rowLabel}>Provident Fund (PF)</Text>
              <Text style={styles.rowValueRed}>
                -{format(Number(record.pf_deduction))}
              </Text>
            </View>
          )}
          {record.esi_deduction > 0 && (
            <View style={styles.row}>
              <Text style={styles.rowLabel}>ESI</Text>
              <Text style={styles.rowValueRed}>
                -{format(Number(record.esi_deduction))}
              </Text>
            </View>
          )}
          {record.tds_deduction > 0 && (
            <View style={styles.row}>
              <Text style={styles.rowLabel}>TDS</Text>
              <Text style={styles.rowValueRed}>
                -{format(Number(record.tds_deduction))}
              </Text>
            </View>
          )}
          {record.pt_deduction > 0 && (
            <View style={styles.row}>
              <Text style={styles.rowLabel}>Professional Tax</Text>
              <Text style={styles.rowValueRed}>
                -{format(Number(record.pt_deduction))}
              </Text>
            </View>
          )}
          {record.days_present < record.working_days && (
            <View style={styles.row}>
              <Text style={styles.rowLabel}>
                Absent Deduction ({record.working_days - record.days_present} days)
              </Text>
              <Text style={styles.rowValueRed}>
                -{format(Number((
                  Number(record.basic_salary) / record.working_days *
                  (record.working_days - record.days_present)
                ).toFixed(0)))}
              </Text>
            </View>
          )}
          {record.pf_deduction === 0 &&
           record.esi_deduction === 0 &&
           record.tds_deduction === 0 &&
           record.pt_deduction === 0 &&
           record.days_present === record.working_days && (
            <View style={styles.row}>
              <Text style={styles.rowLabel}>No deductions</Text>
              <Text style={styles.rowValue}>—</Text>
            </View>
          )}
        </View>

        {/* Net Salary */}
        <View style={styles.totalRow}>
          <Text style={styles.totalLabel}>Net Salary</Text>
          <Text style={styles.totalValue}>
            {format(Number(record.net_salary))}
          </Text>
        </View>

        {/* Footer */}
        <View style={styles.footer}>
          <Text style={styles.footerText}>
            This is a system generated payslip. No signature required.
          </Text>
          <Text style={styles.generatedBy}>
            Generated by PayLeaf
          </Text>
        </View>

      </Page>
    </Document>
  )
}
